# Generated by Django 2.2.3 on 2019-07-27 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('FaName', models.CharField(max_length=100)),
                ('Mobile_no', models.CharField(max_length=12)),
                ('Fa_Mobile_no', models.CharField(max_length=12)),
                ('Email', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=25)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.Sudo')),
            ],
        ),
    ]
