# Generated by Django 2.2.3 on 2019-07-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_auto_20190728_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudo',
            name='Fa_Mobile_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sudo',
            name='Mobile_no',
            field=models.CharField(max_length=100),
        ),
    ]
